give response after nsupdate

diff --git a/.github/workflows/build_deploy_staging.yml b/.github/workflows/build_deploy_staging.yml
--- a/.github/workflows/build_deploy_staging.yml
+++ b/.github/workflows/build_deploy_staging.yml
@@ -122,6 +122,10 @@ jobs:
           zone pilv.tld.ee
           update add auction-"$PR_REF".riigi.pilv.tld.ee 3600 CNAME riigi.pilv.tld.ee
           send
-          quit
           " | nsupdate -k ~/Kgh-runner.infra.tld.ee.+165+27011.key
+          if [ "$?" -eq "0" ]; then
+              echo "CNAME update success"
+          else
+              echo "CNAME update failed"
+          fi
           EOSSH
