Delete dns record after pr closes

diff --git a/.github/workflows/remove_st_after_pr.yml b/.github/workflows/remove_st_after_pr.yml
--- a/.github/workflows/remove_st_after_pr.yml
+++ b/.github/workflows/remove_st_after_pr.yml
@@ -71,4 +71,14 @@ jobs:
           export KUBECONFIG=./kubeconfig
           helm delete auction-st-"$PR_REF" -n auction-staging
           rm kubeconfig
+          echo "server obs.tld.ee
+          zone pilv.tld.ee
+          update delete auction-"$PR_REF".riigi.pilv.tld.ee.
+          send
+          " | nsupdate -k ~/Kgh-runner.infra.tld.ee.+165+27011.key
+          if [ "$?" -eq "0" ]; then
+              echo "CNAME update success"
+          else
+              echo "CNAME update failed"
+          fi
           EOSSH
